package Shapes.sandbox;

/*Generated by MPS */

import javax.swing.JFrame;
import javax.swing.JPanel;
import java.awt.Graphics;
import java.awt.Color;
import java.awt.Dimension;

public class Dibujo extends JFrame {
  private JPanel panel = new JPanel() {

    @Override
    protected void printComponent(Graphics g) {
      super.printComponent(g);
      .setColor(Color.blue);
      .drawOval(10, 20, 30, 30);
      .setColor(Color.red);
      .drawRect(100, 200, 50, 50);
    }
  };
  public void initialize() {
    this.setTitle("Dibujo");
    this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    this.add(panel);
    panel.setPreferredSize(new Dimension(500, 500));
    this.pack();
    this.setVisible(true);
  }
  public static void main(String[] args) {
    Dibujo canvas = new Dibujo();
    canvas.initialize();
  }
}
