package Shapes.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptCanvas = createDescriptorForCanvas();
  /*package*/ final ConceptDescriptor myConceptCircle = createDescriptorForCircle();
  /*package*/ final ConceptDescriptor myConceptColor = createDescriptorForColor();
  /*package*/ final ConceptDescriptor myConceptColorReference = createDescriptorForColorReference();
  /*package*/ final ConceptDescriptor myConceptShapes = createDescriptorForShapes();
  /*package*/ final ConceptDescriptor myConceptSquare = createDescriptorForSquare();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
    deps.extendedLanguage(0x4caf0310491e41f5L, 0x8a9b2006b3a94898L, "jetbrains.mps.execution.util");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptCanvas, myConceptCircle, myConceptColor, myConceptColorReference, myConceptShapes, myConceptSquare);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Canvas:
        return myConceptCanvas;
      case LanguageConceptSwitch.Circle:
        return myConceptCircle;
      case LanguageConceptSwitch.Color:
        return myConceptColor;
      case LanguageConceptSwitch.ColorReference:
        return myConceptColorReference;
      case LanguageConceptSwitch.Shapes:
        return myConceptShapes;
      case LanguageConceptSwitch.Square:
        return myConceptSquare;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForCanvas() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "Canvas", 0xab3f66767593453fL, 0x964cd4f83092d6ebL, 0x43d844e9053becdcL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.parent(0x4caf0310491e41f5L, 0x8a9b2006b3a94898L, 0x40c1a7cb987d20d5L);
    b.origin("r:c8e5c34a-6ec5-4b7d-a3bf-ccdadddd8393(Shapes.structure)/4888733163116555484");
    b.version(3);
    b.aggregate("shapes", 0x43d844e9053becdeL).target(0xab3f66767593453fL, 0x964cd4f83092d6ebL, 0x43d844e9053becd3L).optional(true).ordered(true).multiple(true).origin("4888733163116555486").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCircle() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "Circle", 0xab3f66767593453fL, 0x964cd4f83092d6ebL, 0x43d844e9053becd4L);
    b.class_(false, false, false);
    // extends: Shapes.structure.Shapes
    b.super_(0xab3f66767593453fL, 0x964cd4f83092d6ebL, 0x43d844e9053becd3L);
    b.origin("r:c8e5c34a-6ec5-4b7d-a3bf-ccdadddd8393(Shapes.structure)/4888733163116555476");
    b.version(3);
    b.property("x", 0x43d844e9053becd5L).type(PrimitiveTypeId.INTEGER).origin("4888733163116555477").done();
    b.property("y", 0x43d844e9053becd6L).type(PrimitiveTypeId.INTEGER).origin("4888733163116555478").done();
    b.property("radius", 0x43d844e9053becd7L).type(PrimitiveTypeId.INTEGER).origin("4888733163116555479").done();
    b.alias("circle");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForColor() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "Color", 0xab3f66767593453fL, 0x964cd4f83092d6ebL, 0x43d844e9053cb7afL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:c8e5c34a-6ec5-4b7d-a3bf-ccdadddd8393(Shapes.structure)/4888733163116607407");
    b.version(3);
    b.alias("color");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForColorReference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "ColorReference", 0xab3f66767593453fL, 0x964cd4f83092d6ebL, 0x43d844e9053d25afL);
    b.class_(false, false, false);
    b.origin("r:c8e5c34a-6ec5-4b7d-a3bf-ccdadddd8393(Shapes.structure)/4888733163116635567");
    b.version(3);
    b.associate("target", 0x43d844e9053d25b0L).target(0xab3f66767593453fL, 0x964cd4f83092d6ebL, 0x43d844e9053cb7afL).optional(false).origin("4888733163116635568").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForShapes() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "Shapes", 0xab3f66767593453fL, 0x964cd4f83092d6ebL, 0x43d844e9053becd3L);
    b.class_(false, true, false);
    b.origin("r:c8e5c34a-6ec5-4b7d-a3bf-ccdadddd8393(Shapes.structure)/4888733163116555475");
    b.version(3);
    b.aggregate("color", 0x43d844e9053d25bdL).target(0xab3f66767593453fL, 0x964cd4f83092d6ebL, 0x43d844e9053d25afL).optional(false).ordered(true).multiple(false).origin("4888733163116635581").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSquare() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "Square", 0xab3f66767593453fL, 0x964cd4f83092d6ebL, 0x43d844e9053becd8L);
    b.class_(false, false, false);
    // extends: Shapes.structure.Shapes
    b.super_(0xab3f66767593453fL, 0x964cd4f83092d6ebL, 0x43d844e9053becd3L);
    b.origin("r:c8e5c34a-6ec5-4b7d-a3bf-ccdadddd8393(Shapes.structure)/4888733163116555480");
    b.version(3);
    b.property("upperLeftX", 0x43d844e9053becd9L).type(PrimitiveTypeId.INTEGER).origin("4888733163116555481").done();
    b.property("upperLeftY", 0x43d844e9053becdaL).type(PrimitiveTypeId.INTEGER).origin("4888733163116555482").done();
    b.property("size", 0x43d844e9053becdbL).type(PrimitiveTypeId.INTEGER).origin("4888733163116555483").done();
    b.alias("square");
    return b.create();
  }
}
